name: build-node
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      
      - name: Install dependencies
        run: |
          cd .github/workflows
          npm install
      
      - name: Run application
        run: |
          cd .github/workflows
          node app.js
